// Objective-C API for talking to github.com/lightningnetwork/lnd/mobile Go package.
//   gobind -lang=objc github.com/lightningnetwork/lnd/mobile
//
// File is generated by gobind. Do not edit.

#ifndef __Lndbindings_H__
#define __Lndbindings_H__

@import Foundation;
#include "Universe.objc.h"


@protocol LndbindingsGetStreamResultCallback;
@class LndbindingsGetStreamResultCallback;

@protocol LndbindingsGetStreamResultCallback <NSObject>
- (void)onError:(NSError*)p0;
- (void)onStreamResult:(int64_t)p0;
@end

/**
 * GetInfo returns the GetInfoResponse in JSON format.
 */
FOUNDATION_EXPORT NSString* LndbindingsGetInfo(NSError** error);

FOUNDATION_EXPORT void LndbindingsGetStreamResult(id<LndbindingsGetStreamResultCallback> callback);

FOUNDATION_EXPORT void LndbindingsStart(NSString* appDir);

@class LndbindingsGetStreamResultCallback;

@interface LndbindingsGetStreamResultCallback : NSObject <goSeqRefInterface, LndbindingsGetStreamResultCallback> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (void)onError:(NSError*)p0;
- (void)onStreamResult:(int64_t)p0;
@end

#endif
